services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./data/huggingface:/root/.cache/huggingface
      - ${VAULT_PATH}:/vault:ro
    depends_on:
      - chromadb
    env_file:
      - .env

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=http://localhost:8001

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./data/chromadb:/chroma/chroma
