import { useMemo } from "react";

interface ParsedBody {
  roadmap: string | null;
  accuracy: string | null;
  suggestions: string[];
}

/**
 * Parse the structured body text generated by the backend.
 * Supports two formats:
 * 1. Backend format: heading on its own line, body on next line(s)
 *    ```
 *    反映先ロードマップ: TypeScript > 基礎 > ジェネリクス
 *
 *    正確性チェック:
 *    ジェネリクスの説明は概ね正確です。
 *    ```
 * 2. Frontend spec format: heading and body on the same line
 *    ```
 *    [反映先ロードマップ: TypeScript / 型システム / ジェネリクス]
 *    正確性チェック: ジェネリクスの説明は概ね正確です。
 *    ```
 */
export function parseFeedbackBody(body: string): ParsedBody {
  const out: ParsedBody = { roadmap: null, accuracy: null, suggestions: [] };
  const lines = body.split("\n");
  let mode: "accuracy" | "sugg" | null = null;

  for (const line of lines) {
    const t = line.trim();
    if (!t) {
      // Empty line resets mode (except suggestions which continue)
      if (mode === "accuracy") mode = null;
      continue;
    }

    // Format 1: [反映先ロードマップ: ...]
    const rmBracket = t.match(/^\[反映先ロードマップ:\s*(.+?)\]$/);
    if (rmBracket) {
      out.roadmap = rmBracket[1];
      mode = null;
      continue;
    }

    // Format 2: 反映先ロードマップ: ... (without brackets)
    const rmPlain = t.match(/^反映先ロードマップ:\s*(.+)$/);
    if (rmPlain && !out.roadmap) {
      out.roadmap = rmPlain[1];
      mode = null;
      continue;
    }

    // Accuracy: heading-only line ("正確性チェック:") or inline ("正確性チェック: ...")
    const acInline = t.match(/^正確性チェック:\s*(.+)$/);
    if (acInline) {
      out.accuracy = acInline[1];
      mode = "accuracy";
      continue;
    }
    if (t === "正確性チェック:" || t === "正確性チェック：") {
      mode = "accuracy";
      continue;
    }

    // Suggestions header
    if (t === "改善提案:" || t === "改善提案：") {
      mode = "sugg";
      continue;
    }

    // Suggestion items
    if (mode === "sugg" && t.startsWith("-")) {
      out.suggestions.push(t.replace(/^-\s*/, ""));
      continue;
    }

    // Accuracy body (next-line format or continuation)
    if (mode === "accuracy") {
      out.accuracy = out.accuracy ? out.accuracy + " " + t : t;
      continue;
    }
  }
  return out;
}

interface FeedbackBodyProps {
  body: string;
  expanded: boolean;
  isRead: boolean;
}

export function FeedbackBody({ body, expanded, isRead }: FeedbackBodyProps) {
  const sections = useMemo(() => parseFeedbackBody(body), [body]);
  const mutedText = isRead ? "text-muted-foreground" : "text-foreground";

  if (!expanded) {
    const preview = sections.accuracy
      ? { label: "正確性チェック", text: sections.accuracy }
      : sections.suggestions.length
        ? { label: "改善提案", text: sections.suggestions[0] }
        : null;

    return (
      <>
        {sections.roadmap && (
          <div className="inline-flex items-baseline gap-1.5 min-w-0">
            <span className="shrink-0 text-[11px] font-medium uppercase tracking-[0.06em] text-muted-foreground">
              反映先ロードマップ
            </span>
            <span className={`min-w-0 truncate font-semibold ${mutedText}`}>
              {sections.roadmap}
            </span>
          </div>
        )}
        {preview && (
          <div className="flex items-baseline gap-2 text-[13px] leading-[1.55] min-w-0">
            <span className="shrink-0 text-[11px] font-medium uppercase tracking-[0.06em] text-muted-foreground">
              {preview.label}
            </span>
            <span
              className={`min-w-0 flex-1 line-clamp-2 ${mutedText}`}
            >
              {preview.text}
            </span>
          </div>
        )}
      </>
    );
  }

  return (
    <>
      {sections.roadmap && (
        <div className="inline-flex items-baseline gap-1.5 flex-wrap">
          <span className="text-[11px] font-medium uppercase tracking-[0.06em] text-muted-foreground">
            反映先ロードマップ
          </span>
          <span className={`font-semibold ${mutedText}`}>
            {sections.roadmap}
          </span>
        </div>
      )}
      {sections.accuracy && (
        <div className="flex flex-col gap-1">
          <span className="text-[11px] font-medium uppercase tracking-[0.06em] text-muted-foreground">
            正確性チェック
          </span>
          <span className={`text-[13px] leading-[1.6] ${mutedText}`}>
            {sections.accuracy}
          </span>
        </div>
      )}
      {sections.suggestions.length > 0 && (
        <div className="flex flex-col gap-1">
          <span className="text-[11px] font-medium uppercase tracking-[0.06em] text-muted-foreground">
            改善提案
          </span>
          <ul className="m-0 flex list-none flex-col gap-1 p-0">
            {sections.suggestions.map((s, i) => (
              <li
                key={i}
                className={`relative pl-4 text-[13px] leading-[1.6] ${mutedText} before:absolute before:left-1 before:top-[9px] before:h-1 before:w-1 before:rounded-full before:bg-muted-foreground`}
              >
                {s}
              </li>
            ))}
          </ul>
        </div>
      )}
    </>
  );
}
